version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      DB_HOST: mysql
      DB_DATABASE: db_epdv
      DB_USERNAME: admin_epdv
      DB_PASSWORD: admin123
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    container_name: db_epdv
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: epdv
      MYSQL_USER: admin_epdv
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
